In [4]:
import numpy as np
pi=np.pi
dtr=pi/180    #degree to radian
rtd=180/pi    #radian to degree

class signals():
    
    def __init__(self, aryn=8,dd=0.5,iwave=1,theta=30,snr=-40,n=10):
        
        if(aryn<iwave):
            return "aryn needs to be larger than iwave"
        if(n<=aryn):
            return "aryn needs to be smaller than snap "
        self.aryn=aryn     #number of array element
        
        self.dd=dd     #distance between array element
        
        self.d=np.array(np.linspace(0,(aryn-1)*dd,aryn))    #vector of element
        
        self.iwave=iwave     #number of signal
        
        self.theta=np.array(theta)   #angle of signal
        
        self.snr,self.n=snr,n      #snr and snap number
        
        A=np.exp(-1j*2*pi*np.outer(self.d.T,np.sin(self.theta*dtr))) 
        self.sterV=A
        #steering vector, zero in the front, vertical with array, clockwise rotating 
        
        S=10**(snr/20)*np.random.randn(iwave,n)   #signal value, emulating snapping by augment matrix
        
        X=np.mat(np.dot(A,S)+ np.random.randn(aryn,n))    # received signal

        self.RXX = np.zeros((2,8,8))
        self.RXX[0] = ((X*X.H)/n).real
        self.RXX[1] = ((X*X.H)/n).imag

In [33]:
Info=np.zeros((400000,2,8,8))
lable=np.zeros((400000,1))
for i in np.linspace(0,399999,400000,dtype='int'):
    B= 0
    C=50
    E=np.random.random_integers(-90,90,1).tolist()[0]
    A=signals(aryn=8, dd=0.5, iwave=1, theta=E,snr=B,n=C)
    lable[i]=E
    Info[i]=A.RXX

np.save("E:/modules/data/Covariance5.npy",Info)
np.save("E:/modules/data/lable5.npy",lable)

<ipython-input-33-96aa0431931c>:6: DeprecationWarning: This function is deprecated. Please call randint(-90, 90 + 1) instead
  E=np.random.random_integers(-90,90,1).tolist()[0]


In [86]:
H[399999]

array([[ 1.08453026,  0.03256283,  0.10743503,  0.09966227,  0.02051906,
         0.04795611, -0.11002792,  0.04262329],
       [ 0.03256283,  0.88457943,  0.23244121,  0.18595787, -0.04671043,
         0.06493979, -0.06690688, -0.1220595 ],
       [ 0.10743503,  0.23244121,  1.06970513, -0.09113777,  0.1419485 ,
         0.11042261,  0.00481855,  0.02972232],
       [ 0.09966227,  0.18595787, -0.09113777,  0.96074887, -0.14395237,
        -0.02416983,  0.02976112, -0.1705651 ],
       [ 0.02051906, -0.04671043,  0.1419485 , -0.14395237,  1.31409623,
         0.03891663, -0.14514482, -0.07025107],
       [ 0.04795611,  0.06493979,  0.11042261, -0.02416983,  0.03891663,
         1.19239404, -0.00398677, -0.01056506],
       [-0.11002792, -0.06690688,  0.00481855,  0.02976112, -0.14514482,
        -0.00398677,  1.08427527, -0.10199353],
       [ 0.04262329, -0.1220595 ,  0.02972232, -0.1705651 , -0.07025107,
        -0.01056506, -0.10199353,  0.80102587]])

In [87]:
AN=np.load("E:/modules/data/lable2.npy")

In [88]:
AN[399999]

array([5.])

In [27]:
    A=signals(aryn=8, dd=0.5, iwave=1, theta=30,snr=0,n=50)

In [28]:
A.RXX[1]

array([[ 0.00000000e+00,  1.10137395e+00,  6.23987693e-16,
        -1.10137395e+00, -1.24797539e-15,  1.10137395e+00,
         2.36107136e-15, -1.10137395e+00],
       [-1.10137395e+00,  0.00000000e+00,  8.99710262e-01,
         3.31256971e-01, -7.69388645e-01, -2.32207018e-01,
         1.26798971e+00,  5.25391912e-02],
       [-6.23987693e-16, -8.99710262e-01,  0.00000000e+00,
         8.99710262e-01,  5.83568568e-16, -8.99710262e-01,
        -1.21037016e-15,  8.99710262e-01],
       [ 1.10137395e+00, -3.31256971e-01, -8.99710262e-01,
         0.00000000e+00,  7.69388645e-01, -9.90499531e-02,
        -1.26798971e+00,  2.78717780e-01],
       [ 1.24797539e-15,  7.69388645e-01, -5.83568568e-16,
        -7.69388645e-01,  0.00000000e+00,  7.69388645e-01,
         2.12608579e-16, -7.69388645e-01],
       [-1.10137395e+00,  2.32207018e-01,  8.99710262e-01,
         9.90499531e-02, -7.69388645e-01,  0.00000000e+00,
         1.26798971e+00, -1.79667827e-01],
       [-2.36107136e-15, -1.267989

In [3]:
Info=np.zeros((1000000,2,8,8))
lable=np.zeros((1000000,1))
for i in np.linspace(0,999999,1000000,dtype='int'):
    B = np.random.random_integers(-20,0,1).tolist()[0]
    C = 50
    E = np.random.random_integers(-60,60,1).tolist()[0]
    A = signals(aryn = 8, dd = 0.5, iwave = 1, theta = E,snr = B,n = C)
    lable[i] = B
    Info[i] = A.RXX

np.save("E:/modules/data/Covariance60_randomdb_-20~0_2.npy",Info)
np.save("E:/modules/data/lable60_randomdb_-20~0_2.npy",lable)

<ipython-input-3-07bc578c6797>:4: DeprecationWarning: This function is deprecated. Please call randint(-40, 0 + 1) instead
  B = np.random.random_integers(-40,0,1).tolist()[0]
<ipython-input-3-07bc578c6797>:6: DeprecationWarning: This function is deprecated. Please call randint(-60, 60 + 1) instead
  E = np.random.random_integers(-60,60,1).tolist()[0]


In [20]:
120*(np.random.rand()-0.5)

42.729182715007624

In [3]:
lable

array([[-20.],
       [  0.],
       [  0.],
       ...,
       [ -2.],
       [ -1.],
       [-10.]])